-- ═══════════════════════════════════════════════════════════════════════════
-- Tabla para las Guardias de Agosto
-- Pega este código en el SQL Editor de Supabase y presiona "Run".
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.guardias_agosto (
  id bigint generated by default as identity primary key,
  seminarista_id text not null unique,
  seminarista_nombre text not null,
  guardia_id text not null,
  created_at timestamptz not null default now()
);

alter table public.guardias_agosto enable row level security;

create policy "lectura publica"  on public.guardias_agosto for select using (true);
create policy "insertar publico" on public.guardias_agosto for insert with check (true);
create policy "cambiar publico"  on public.guardias_agosto for update using (true) with check (true);
create policy "salir publico"    on public.guardias_agosto for delete using (true);

-- Habilita las actualizaciones en tiempo real (todos ven los cambios al instante)
alter publication supabase_realtime add table public.guardias_agosto;
